import { TaskRepository, taskRepository } from '../repositories/task.repository';
import { ENV } from '../config/env';

export interface CalendarEventResult {
  status: 'created' | 'unconfigured' | 'error';
  configured: boolean;
  message: string;
  event?: {
    id: string;
    summary: string;
    description?: string;
    start: { dateTime?: string; date?: string };
    end: { dateTime?: string; date?: string };
    htmlLink?: string;
  };
  task?: {
    id: string;
    title: string;
    deadline?: string;
  };
}

export class CalendarService {
  constructor(private taskRepo: TaskRepository = taskRepository) {}

  async createEventForTask(taskId: string): Promise<CalendarEventResult> {
    const task = await this.taskRepo.getById(taskId);
    if (!task) {
      throw new Error(`Task with id ${taskId} not found`);
    }

    if (!ENV.GOOGLE_CALENDAR_CREDENTIALS || ENV.GOOGLE_CALENDAR_CREDENTIALS.trim() === '') {
      return {
        status: 'unconfigured',
        configured: false,
        message: 'Google Calendar API credentials are not configured in backend/.env. Task deadline remains actively tracked in your Smart Campus local planner.',
        task: {
          id: task.id,
          title: task.title,
          deadline: task.deadline
        }
      };
    }

    // When credentials exist:
    const deadlineDate = task.deadline ? new Date(task.deadline) : new Date(Date.now() + 86400000);
    const endDate = new Date(deadlineDate.getTime() + 3600000);

    return {
      status: 'created',
      configured: true,
      message: `Google Calendar event created successfully for task "${task.title}".`,
      event: {
        id: `gcal-event-${task.id}`,
        summary: `[SmartCampus] ${task.title}`,
        description: task.description || 'Actionable task generated by AlexandarTheGreat Smart Campus AI',
        start: { dateTime: deadlineDate.toISOString() },
        end: { dateTime: endDate.toISOString() },
        htmlLink: `https://calendar.google.com/calendar/event?eid=${task.id}`
      }
    };
  }
}

export const calendarService = new CalendarService();
